### ISSUE TITLE
graphql playground

### ISSUE THREAD

**Issue by raymclee** [PabloSzx/next-fastify-mercurius-vercel#1]
does playground work on vercel?

**Comment by PabloSzx** [comment]
yes, but it has to be enabled, and the current playground implementation is a little buggy since it has been basically deprecated, see https://github.com/graphql/graphql-playground/issues/1143, and I recommend using altair instead, which is better is pretty much every way https://mercurius.dev/#/docs/plugins?id=altair-fastify-plugin

**Comment by raymclee** [comment]
can you please let me know how to make playground work?

**Comment by PabloSzx** [comment]
this example already is using altair, which is better than playground, the route is /api/altair

https://next-fastify-mercurius.vercel.app/api/altair
